import { LOCAL_STORAGE_KEYS } from '../constants.js';
import { showToast } from './toastService.js';

let learningPaths = [];

/**
 * Loads learning paths from localStorage.
 * @private
 */
function loadPaths() {
    try {
        const stored = localStorage.getItem(LOCAL_STORAGE_KEYS.LEARNING_PATHS);
        learningPaths = stored ? JSON.parse(stored) : [];
    } catch (e) {
        console.error("Failed to load learning paths:", e);
        learningPaths = [];
    }
}

/**
 * Saves the current learning paths to localStorage.
 * @private
 */
function savePaths() {
    try {
        localStorage.setItem(LOCAL_STORAGE_KEYS.LEARNING_PATHS, JSON.stringify(learningPaths));
    } catch (e) {
        console.error("Failed to save learning paths:", e);
    }
}

/**
 * Initializes the learning path service by loading data from localStorage.
 * Should be called once on application startup.
 */
export function init() {
    loadPaths();
}

/**
 * Retrieves all saved learning paths.
 * @returns {Array<object>} An array of learning path objects.
 */
export function getAllPaths() {
    return learningPaths;
}

/**
 * Finds a specific learning path by its ID.
 * @param {string} id - The ID of the learning path.
 * @returns {object|undefined} The found learning path object, or undefined.
 */
export function getPathById(id) {
    return learningPaths.find(p => p.id === id);
}

/**
 * Creates and saves a new learning path.
 * @param {string} goal - The user-defined goal for the learning path.
 * @param {Array<object>} path - The array of steps generated by the AI.
 * @returns {object} The newly created learning path object.
 */
export function addPath(goal, path) {
    const newPath = {
        id: `path_${Date.now()}`,
        goal,
        path,
        createdAt: new Date().toISOString(),
        currentStep: 0,
    };
    learningPaths.unshift(newPath); // Add to the beginning for chronological display
    savePaths();
    showToast('New learning path saved!');
    return newPath;
}

/**
 * Advances the user's progress in a learning path to the next step.
 * @param {string} pathId - The ID of the learning path to update.
 */
export function completeStep(pathId) {
    const path = getPathById(pathId);
    if (path && path.currentStep < path.path.length - 1) {
        path.currentStep += 1;
        savePaths();
        showToast('Step completed! Well done.');
    } else if (path && path.currentStep === path.path.length -1) {
        // Mark the entire path as complete
        path.currentStep = path.path.length;
        savePaths();
        showToast('Learning path completed! Congratulations!', 'success');
    }
}

/**
 * Deletes a learning path from storage.
 * @param {string} pathId - The ID of the learning path to delete.
 */
export function deletePath(pathId) {
    learningPaths = learningPaths.filter(p => p.id !== pathId);
    savePaths();
    showToast('Learning path deleted.');
}